# Railway deployment configuration for String Analyzer Service

[build]
  command = "pip install -r requirements.txt"

[start]
  command = "uvicorn main:app --host 0.0.0.0 --port $PORT"

# Railway uses $PORT environment variable for web services
# No additional environment variables required for this project
